### ISSUE TITLE
Multiple versions of card art icon? (E.g. to support dark mode)

### ISSUE THREAD

**Issue by danyao** [w3c/secure-payment-confirmation#1]
The code snippet in the explainer suggests that the caller can provide multiple icons. Wouldn't one icon be sufficient?

```
const publicKeyCredentialCreationOptions = {
  paymentInstrument: {
    name: 'Mastercard****4444',
    icons: [{
  	  'src': 'icon.png',
  	  'sizes': '48x48',
  	  'type': 'image/png',
    }],
  },
...
```

**Comment by adrianhopebailie** [comment]
Maybe the right thing is to be able to provide multiple instruments with a single icon per instrument?

Is the expectation that the provided icon will be high-res and the browser will scale it appropriately?

What about dark-mode 😄

**Comment by danyao** [comment]
> Maybe the right thing is to be able to provide multiple instruments with a single icon per instrument?

Filed #13 to track the instrument cardinality question. 😎 
 
> Is the expectation that the provided icon will be high-res and the browser will scale it appropriately?

Yeah. Browser will download and save these icons at credential enrollment time. So we'll probably only save the scaled down version.

> What about dark-mode 😄

Good point. In that case, we should probably also specify the purpose of the icon.

**Comment by marcoscaceres** [comment]
probably want to use https://github.com/w3c/image-resource

**Comment by ianbjacobs** [comment]
I think this issue may still be relevant at authentication time (even if icon info is not set at enrollment). For example, how would dark mode be handled? Different icon sizes?

**Comment by JeanDim** [comment]
On the 3DS 2.3.0 protocol, dark mode has been take into account for the payment system and issuer logo to be display. 
If SPC is triggered during a frictionless 3DS flow (AReq/ARes level) the ACS MAY (optional) populate the spcTransData object with issuer (issuerImageSpc) and payment system (psImageSpc) dark mode logo by referencing URLs or Data URl with b64 encoded format. 

For the  3DS challenge flow (CReq/CRes level ) for APP-based (could be JS SDK), dark mode is also possible (optional field)  for issuer and payment system logo.  For browser-based, the ACS would defined directly (outside 3DS protocol)  the logo to use I guess

**Comment by ianbjacobs** [comment]
After discussion with the chairs and editors we have concluded that the primary use case here is to support "dark mode." The dark mode use case can be addressed by using client-side JavaScript, and thus we are closing this issue until we hear additional use cases.
