### ISSUE TITLE
Let's be explicit about what happens when an authenticator roams

### ISSUE THREAD

**Issue by jcjones** [w3c/secure-payment-confirmation#12]
When we create a new payment credential using your roaming credential, it's implied that the browser stores the credential `displayName` and `icon` so that when it's presented as an authentication option in the future, the browser can provide the user that useful bit of context that "this will use your Blue Authenticator to approve putting this purchase on your Yellow Card ending in 9999."

Moving the Blue Authenticator to another computer though and doing the same operation with the same account will prvoide a compatible `credentialId` that the browser can then use to approve this new purchase ... but there's no knowledge of what that `credentialId` would be approving _for_. E.g., the context would be, "This will use your Blue Authenticator to approve for an unknown payment type."

Browsers could sync that data around, but many people have many reasons to not sync, so this is a "normal" edge case. What _should_ happen when a browser can't display useful context? Ignore that credential ID?

**Comment by danyao** [comment]
This is a great question! We are skirting it now by restricting this only to platform authenticators. 😅 

In the long term, I think the best user experience would be for `displayName` and `icon` to be saved in the authenticator. I wonder if we can leverage [WebAuthn extensions](https://www.w3.org/TR/webauthn/#extensions) for this.

Another blocker before we can expand to roaming authenticators is for WebAuthn API to provide a mechanism to filter only authenticators that support 2-factor (e.g. USB authenticator with biometrics sensor). I believe all payment use cases would need 2-factor, and the `transport` option is not really meant to differentiate this capability.

**Comment by ianbjacobs** [comment]
I'm going to close this issue in favor of issue #92, which touches on the SPC design goal of removing the need for browser-stored information (for instruments, certainly, and ultimately for credential ids as well). Issue #92 resolution should also eventually help us accommodate roaming authenticators.

**Comment by stephenmcgruer** [comment]
From the SPC spec side, there are two concrete changes we would likely have to make to allow roaming authenticators:

1. Remove the check for `authenticatorAttachment` in the [client extension processing steps](https://w3c.github.io/secure-payment-confirmation/#client-extension-processing-registration).
2. Rework how we deal with the [steps to determine if a credential is SPC-enabled](https://w3c.github.io/secure-payment-confirmation/#steps-to-determine-if-a-credential-is-spc-enabled) and [steps to silently determine if a credential is available for the current device](https://w3c.github.io/secure-payment-confirmation/#steps-to-silently-determine-if-a-credential-is-available-for-the-current-device) to support remote authenticators.

(This presumes also that remote authenticators support (2), e.g. via some CTAP protocol change. Under discussion in WebAuthn currently.)

The tricky part is obviously step (2); we need a different approach where we would continuously poll for authenticator devices that support any of the passed in credentials. However this is somewhat at odds with the goal of SPC to have a conditionally-shown transaction UX (i.e., that is only shown if the user can definitely use SPC on this device).

One possible workaround we've considered internally is to have a 'fallback' experience for remote authenticators. This isn't the best experience, and I'm open to other ideas, but it would at least enable not-yet-available remote authenticators without hurting the 'happy path' of platform or immediately-available remote authenticators. A mock:

![image](https://user-images.githubusercontent.com/153264/156415035-570da2c7-732a-4932-9ad5-42f6c55abda4.png)

**Comment by Goosth** [comment]
Thanks Stephen,

Yes, I support this proposal.

**Comment by ianbjacobs** [comment]
Discussed with WebAuthn WG today [1]. More discussion needed in WPWG, in conjunction with fallback UX discussions.

[1] https://www.w3.org/2023/05/03-webauthn-irc

**Comment by Vargas1205** [comment]
Mis pagos

**Comment by bhjelm-yubico** [comment]
Below are requirements for supporting discoverable credentials on a roaming authenticator shared on the May 7 call.

- SPC SHALL follow the [WebAuthn flow](https://www.w3.org/TR/webauthn/images/webauthn-authentication-flow-01.svg) for discovering authenticators and identifying the correct authenticator to be used.
- The roaming authenticator SHALL be paired with an application or through a FIDO credential registration.
- Persistent CTAP PUAT (pinUvAuthToken) SHALL be supported and the discoverable credential(s) on the roaming authenticator SHALL be cached.
- SPC SHALL support providing a filtered list of eligible credentials.
- SPC SHALL support cross-origin/payment credential flag (in SPC and CTAP).

**Comment by rlin1** [comment]
I support that.
Two clarifications:
1. cross-origin payment credential flag is already part of CTAP: https://fidoalliance.org/specs/fido-v2.3-ps-20260226/fido-client-to-authenticator-protocol-v2.3-ps-20260226.html#sctn-thirdPartyPayment-extension
2. non-discoverable credentials SHALL be supported - discoverable credentials SHALL be cached.

**Comment by stephenmcgruer** [comment]
> SPC SHALL follow the WebAuthn flow for discovering authenticators and identifying the correct authenticator to be used.

I would love "us" (the group, I don't know when I will have time) to properly look into this and consider the implications and what would be required to get here. 

Right now from a specification point of view, SPC has the following:

https://w3c.github.io/secure-payment-confirmation/#sctn-steps-to-respond-to-a-payment-request
- Builds a `PublicKeyCredentialRequestOptions` with all the credentials passed into SPC (albeit with each of them set to a transports sequence of `internal`)
- Calls credential management's [Request a Credential](https://w3c.github.io/webappsec-credential-management/#abstract-opdef-request-a-credential) algorithm with that `PublicKeyCredentialRequestOptions`
    - This should end up in WebAuthn's [Discover from External Source](https://w3c.github.io/webauthn/#sctn-discover-from-external-source) I think

https://w3c.github.io/secure-payment-confirmation/#client-extension-processing-authentication
- Modifies the WebAuthn flow in a few ways (adds BBK info, creates a payments cryptogram output, allows third-party use of the credential)

So **in theory** this runs the normal WebAuthn authenticator discovery *I think*, however we also know that in practice this is not what Chromium does and importantly likely not what would result in the expected SPC user flow. I think the two main requirements we are trying to hit are:

1. User sees no other UX before the SPC Transaction Dialog (e.g. no initial authenticator or passkey selector screen)
2. After confirming SPC Transaction Dialog, user should have as few subsequent dialogs as possible to finish their authentication (most partners want this number to be **zero** and to have the SPC dialog also be the WebAuthn one, which isn't generally possible, but they definitely don't want the number to be above **one**, which means we have tried to avoid any post-SPC authenticator or passkey selector screens.
3. User ~never sees the WebAuthn "we couldn't find any authenticator" dialog.

This has caused us to somewhat "make up" concepts at the SPC spec level (https://w3c.github.io/secure-payment-confirmation/#steps-to-silently-determine-if-an-spc-credential-is-third-party-enabled and https://w3c.github.io/secure-payment-confirmation/#steps-to-silently-determine-if-a-credential-is-available-for-the-current-device) and similarly make implementation choices in Chromium which do currently restrict which authenticators are used.

**Comment by stephenmcgruer** [comment]
> The roaming authenticator SHALL be paired with an application or through a FIDO credential registration.

Can you clarify what this means, please? I'm not familiar with what it means to 'pair' a roaming authenticator.

**Comment by stephenmcgruer** [comment]
> Persistent CTAP PUAT (pinUvAuthToken) SHALL be supported and the discoverable credential(s) on the roaming authenticator SHALL be cached.

Shall be cached by whom? Do you expect this to be a user agent level concept in either the SPC and/or WebAuthn specification, or potentially a WebAuthn "client" concept (which can be the OS iiuc)? Same question re pinUvAuthToken, I'm not familiar with that extension.

cc @nsatragno

**Comment by stephenmcgruer** [comment]
> SPC SHALL support providing a filtered list of eligible credentials.

I think it already does, in https://w3c.github.io/secure-payment-confirmation/#dom-securepaymentconfirmationrequest-credentialids - do you think there is something missing there?

**Comment by stephenmcgruer** [comment]
> SPC SHALL support cross-origin/payment credential flag (in SPC and CTAP).

Again one thing I would *love* for the group to take on is looking into and thinking about the mess we got ourselves into (this was really my bad :( ) over the overlap and differences between the SPC-level `payment` extension (https://w3c.github.io/secure-payment-confirmation/#sctn-payment-extension-registration) and the FIDO-level `thirdPartyPayment` extension (https://fidoalliance.org/specs/fido-v2.3-ps-20260226/fido-client-to-authenticator-protocol-v2.3-ps-20260226.html#sctn-thirdPartyPayment-extension). See also https://github.com/w3c/secure-payment-confirmation/issues/157

Unfortunately it is a mess, and needs someone to think very carefully about what the current situation is as well as what we would want it to be, and how we might get there.

**Comment by bhjelm-yubico** [comment]
> > The roaming authenticator SHALL be paired with an application or through a FIDO credential registration.
> 
> Can you clarify what this means, please? I'm not familiar with what it means to 'pair' a roaming authenticator.

WebAuthn does not define a "pairing" concept for roaming authenticators in the way the requirement implies. The challenge is that:

- If "pairing" means a prior FIDO credential registration (i.e., the credential already exists on the roaming authenticator), it's already implied by the **credentialIds** flow (the RP provides credential IDs that it already knows about).
- If "pairing" means some out-of-band device association (e.g., Bluetooth bonding, NFC
tap-to-pair), that's an OS/platform concept outside the scope of both WebAuthn and SPC.

An action here would be to define the required precondition order to specify this requirement normatively.

**Comment by stephenmcgruer** [comment]
Hey folks; as an update, I've put together two related explainers that I think are relevant for this issue:

- https://github.com/w3c/secure-payment-confirmation/pull/340
- https://github.com/w3c/secure-payment-confirmation/pull/338

I'm waiting on @ianbjacobs ' input for how we want to best handle feedback/discussion on these two proposals, but wanted to highlight them here ASAP so folks are aware.
