### ISSUE TITLE
Require AuthenticatorSelection's residentKey for registration

### ISSUE THREAD

**Issue by maxlgu** [w3c/secure-payment-confirmation#129]
In 1.2.1 Registration, we should specify that AuthenticatorSelection’s's residentKey is a required property.

**Comment by maxlgu** [comment]
@rsolomakhin , could you add some references to support this issue?

**Comment by rsolomakhin** [comment]
Here is a link to the discoverable credential / resident key field values: https://w3c.github.io/webauthn/#dom-authenticatorselectioncriteria-residentkey. I could not find any information in this repository that mentions that Chrome requires it. That's a bit strange. @stephenmcgruer  - where should this information be added?
