### ISSUE TITLE
Document current implementation limitations in Notes

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#130]
Per discussion with @rsolomakhin today, we may need to update algorithm descriptions with whatever is hard-coded today in the Chrome implementation (e.g., platform authenticator, user identity support).

We already do this for " This algorithm hard-codes "required" as the value for userVerification"

@rsolomakhin would you mind doing a pull request with Notes regarding the other two hard-coded expectations? 

Thanks!

**Comment by rsolomakhin** [comment]
I've added some clarifications in https://github.com/w3c/secure-payment-confirmation/commit/db561eb0ebb2573111cfc9b38b6ed6d8ea71d254. Please help to wordsmith if needed.

**Comment by ianbjacobs** [comment]
Closing this after editorial tweaks to your clarifications. Thanks!
