### ISSUE TITLE
How to handle stale displayName and icon?

### ISSUE THREAD

**Issue by danyao** [w3c/secure-payment-confirmation#14]
@adrianhopebailie raised this in https://github.com/rsolomakhin/secure-payment-confirmation/issues/10#issuecomment-666970228:

> I worry about the browser-side mapping of instruments to credentials and the high likelihood that the data gets stale.

The simplest approach is for the issuer to update an existing credential with a new label and icon when the user visits the issuer's website. But I wonder if a user cannot be guaranteed to revisit. Perhaps some kind of push mechanism for the RP to update the instrument label and icon would be helpful.

**Comment by adrianhopebailie** [comment]
Wouldn't this be a lot easier to manage if instruments were managed by the RP Payment Handler and this could have a refresh instruments event that could be invoked by the browser occasionally?

**Comment by danyao** [comment]
> Wouldn't this be a lot easier to manage if instruments were managed by the RP Payment Handler and this could have a refresh instruments event that could be invoked by the browser occasionally?

@btidor-stripe had said a few times that it's important to not require an RP Payment Handler in SPC because many ACS (who will be RPs in SPC) cannot easily stand up service workers.

**Comment by btidor-stripe** [comment]
Yep, having a lightweight integration would be ideal. One way to do this would be for the RP to publish a JSON document containing the payment instrument data. The browser could load the document during registration and poll it periodically for updates:

```
{
  "id": "card_1HjWCQDMts5GS4hiDpJnadxq",
  "deleted": false,
  "displayName": "Mastercard ····4444",
  "icon": "icon.png",
  // + future data for the combined flow
}
```

**Comment by Goosth** [comment]
Hi @btidor-stripe. Interesting proposal. Is the idea to have a single manifest file (JSON doc) for all Id's served by an RP (the Issuer), or would there be a separate JSON document for each 'user' or 'card'?

And how would the linking between a payment mechanism and a credential (Fido token) be setup? Still with a navigator.credentials.create instruction by the RP? This would this then be to allow 
* Updating for Displayname and Icons
* Removal of old entries?

**Comment by btidor-stripe** [comment]
Hi @Goosth, that was my idea -- having a separate manifest per instrument! There's a lot of flexibility in how the manifest could be registered, but linking it in the `navigator.credentials.create` call makes sense to me. Like you said, this would enable the issuer to update the displayName and icon, as well as remotely deprovision the instrument (e.g. to clean up when a user freezes or de-registers a device from their online banking portal).

This is just one suggestion, though!

**Comment by adrianhopebailie** [comment]
In the architecture that @ianbjacobs and I were working on the `PaymentCredential` (somewhat akin to the existing Payment Handler concept of "instruments") could have a URL as an identifier.

This would allow the browser to refresh the data at any time by simply doing a fetch on the URL.

The fetch would need to include client credentials (now I mean cookies... credential is VERY overloaded) it has for the RP origin otherwise anyone could fetch the data (possibly not an issue but need to explore).

**Comment by ianbjacobs** [comment]
The API has evolved so that instrument display information is provided as input at authentication time. I am going to close this issue.
