### ISSUE TITLE
10.2 missing parenthesis

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secure-payment-confirmation#141]
after Relying Party

**Comment by stephenmcgruer** [comment]
Apologies Sam, I don't see a missing parenthesis after Relying Party in https://w3c.github.io/secure-payment-confirmation/#sctn-privacy-probing-credential-ids, can you clarify?

![image](https://user-images.githubusercontent.com/153264/136377671-9315f75a-7061-4e83-a6cf-a4450b584be0.png)

**Comment by samuelweiler** [comment]
I wonder if we're on different branches:
` (who now may not even be the <a data-link-type="dfn" href="https://w3c.github.io/webauthn/#relying-party" id="ref-for-relying-party②⑥">Relying Party</a> to distinguish between these cases:</p>`

<img width="747" alt="Screen Shot 2021-10-07 at 7 55 24 AM" src="https://user-images.githubusercontent.com/24963390/136379700-a7bc9aae-195a-427b-839f-4f477941dd11.png">

**Comment by samuelweiler** [comment]
Ah, yes.  Somehow I had switched to the FPWD version rather than the editors draft.
