### ISSUE TITLE
11.2 define the mitigation

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secure-payment-confirmation#142]
The attack in 10.2 is clear, as is the goal ("make sure not to enable malicious callers... to distinguish between these cases").

But the methods of getting there are not defined.  Instead of "If the URL is accessed then the caller can conclude that at least one of the passed credentials is available to the user", how about an instruction: "do not load the URL until"?  Presumably that instruction should be elsewhere in the doc, to be read contemporaneously with other process test.  Are any other mitigations needed to achieve the goal?

**Comment by stephenmcgruer** [comment]
(Note: this is now [11.2](https://w3c.github.io/secure-payment-confirmation/#sctn-privacy-probing-credential-ids))

**Comment by samuelweiler** [comment]
I'm glad to see the explicit instructions in what is now 4.1.4.  

1) I'd like 11.2 to point at 4.1.4 (e.g. "here's now to achieve this"

2) Are the instructions in 4.1.4 sufficient to mitigate all leaks?  From your text, I'm inferring that is it not.  What else is needed?

**Comment by ianbjacobs** [comment]
Thank you, @samuelweiler, for the recommendation to tighten up the normative language, now integrated. We hope this resolves the current issue.
