### ISSUE TITLE
PROPOSAL 2: No Payment Handler Flow

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/secure-payment-confirmation#17]
As a counter-proposal to #15 here is a proposal that would require no Payment Handlers (i.e. they could potentially be deprecated entirely) but would require that instruments are stored by RPs in the browser using an ID that is both "routable" by a merchant and opaque enough that it is not sensitive to share.

This is a minor modification to the existing Secure Payment Confirmation (SPC) proposal.

## Advantages:

 1. No need for Payment Handlers = very simple to implement for RPs
 2. Lower implementation and maintenance burden for browsers
 3. Much simpler Payment Request API (no need to support "payment method data" and can possibly exclude shipping details etc)
 4. Simple fallback to rendering an RP provided URL inside a modal dialogue

## Disadvantages:

 1. Need a strategy to prevent instrument identifiers becoming global user identifiers
 2. No PH = no support for delegated shipping details etc

## Assumptions:

1. The RP (bank/issuer/wallet) registers payment instruments in the browser at some time when the user has authenticated themselves (e.g. login to Internet banking/wallet, complete a previous transaction)
2. The instrument identifier is "routable" (i.e. can be used by a merchant to route an authorization request to the RP to get a challenge or fallback URL). E.g. A format-preserving tokenized card or URL
3. The instrument identifier is opaque (does not reveal private information about the user) as it will be revealed to the merchant before SPC when the instrument is selected by the user from a browser-rendered instrument selector

## Questions:

1. Can the instrument identifier be easily rotated so it is not a global identifier shared by the browser with multiple merchants?
2. How does an RP register payment instruments that will not be used with Secure Payment Confirmation but where the URL for the fallback flow is not same-origin as the RP? (e.g. ACS server for capturing SMS OTP is at different origin to issuer who is the RP)
3. How will an RP manage the instruments installed in the user's browser? Will they be able to enumerate them, delete them etc?
4. Do we need a flow that is equivalent to JIT installation of a Payment Handler?

## Enrollment

RPs (issuers, wallets etc) will register payment instruments in a users browser during an enrolment flow which involves calling the WebAuthn `create` API to create a new `PaymentCredential`.

A `PaymentCredential` is a new type of credential which MAY be linked to a `PublicKeyCredential` (which may be implicitly created when registering the `PaymentCredential`). It contains payment instrument meta-data (i.e. a label and icon) and is mapped to one or more payment methods.

It will be possible to create a new `PaymentCredential` linked to an existing `PublicKeyCredential`. In this case the browser will invoke the authenticator's authentication flow using the details of the existing credential (as opposed to the registration flow which creates a new credential on the authenticator).

It will be possible to create a `PaymentCredential` that is not linked to a `PublicKeyCredential`. This instrument will appear in the browser-rendered instrument selector when appropriate but can't be used to invoke Secure Payment Confirmation. If a user selects one of these instruments then the merchant can only invoke the fallback authN flow by passing in an RP provided URL to render.

Whenever an RP registers an instrument there will be a user interaction whereby the user confirms the registration and their intent to use this for payments in the future. If the credential is linked to a `PublicKeyCredential` this will also involve a user interaction with their authenticator as with existing WebAuthn registration and authentication flows.

The installed `PaymentCredentials` serve multiple functions:

1. They are used by the browser to present the user with an instrument selection list when the merchant calls PR API without providing a list of instrument identifiers. The list is filtered based on the payment methods provided by the merchant and those mapped to the credential.
2. The label and icon are used on the Secure Payment Confirmation screen.
3. The label and icon are rendered by the browser as part of the modal dialogue that renders the fallback URL when Secure Payment Confirmation is skipped/fails.
4. The fallback flow is only allowed if the provided URL is same-origin with the credential RP.

```webidl
[SecureContext, Exposed=Window]
interface PaymentCredential : Credential {
};

partial dictionary CredentialCreationOptions {
  PaymentCredentialCreationOptions securePayment;
};

dictionary PaymentCredentialCreationOptions {
  // |instrumentId| is a caller provided ID for the payment instrument 
  //  to which the new PaymentCredential should be bound. It should be 
  //  an opaque string generated using a payment network specific algorithm 
  //  that allows the network to identify the issuer of the instrument 
  //  and the issuer to identify the account associated with this
  //  instrument. (e.g. form-preserving card token or URL)

  required DOMString instrumentId;
  required DOMString displayName;
  required USVString icon;
  required sequence<USVString> paymentMethods;
  PaymentCredentialPublicKeyOptions createPublicKeyCredentialOptions
  PublicKeyCredentialDescriptor existingPublicKeyCredential;
};

// Either |createPublicKeyCredentialOptions| or |existingPublicKeyCredential| 
//  or both must be provided.
// If both are provided then the browser should create the credential if 
//  the existing credential doesn't exist.

dictionary PaymentCredentialPublicKeyCreationOptions {
  required PublicKeyCredentialRpEntity rp;
  required BufferSource challenge;
  required sequence<PublicKeyCredentialParameters> pubKeyCredParams;
  unsigned long timeout;
  
  // PublicKeyCredentialCreationOption attributes that are intentionally omitted:
  // user: For a PaymentCredential, |instrument| is analogous to |user|.
  // excludeCredentials: No payment use case has been proposed for this field.
  // attestation: Authenticator attestation is considered an anti-pattern 
  //  for adoption so will not be supported.
  // extensions: No payment use case has been proposed for this field.
};
```
Example usage:

```javascript
const securePaymentConfirmationCredentialCreationOptions = {
 instrumentId: "Q1J4AwSWD4Dx6q1DTo0MB21XDAV76",
 displayName: 'Mastercard····4444',
 icon: 'icon.png',
 paymentMethods: ["https://mastercard.com/pay", "https://clicktopay.com"]
 existingCredential: {
    type: "public-key",
    id: Uint8Array.from(credentialId, c => c.charCodeAt(0))
 },
 publicKeyCreationOptions: {
  challenge,
  rp,
  pubKeyCredParams,
  timeout
 }
};

// Bind new credential to |credentialId|, or create a new credential 
//  if |credentialId| doesn't exist.
const credential = await navigator.credentials.create({
  securePayment: securePaymentCredentialCreationOptions
});

```

## Payment

When a user visits a merchant there are two possible flows before Secure Payment Confirmation (or the fallback flow) is invoked.

### User Provided Instrument

 1. The merchant gets the instrument selection from the user via a form or other mechanism (e.g. selection of a card on file)
 2. The merchant sources a set of valid instrument identifiers, an optional challenge, and an optional fallback URL from the payment system.
 3. The merchant creates a Payment Request and passes the instrument identifiers into the constructor.
 4. The merchant calls `canMakePayment` and the browser returns a "truthy" response if one of the provided instrument identifiers identifies an installed `PaymentCredential` that supports one of the merchant provided payment methods. If there is an instrument linked to a `PublicKeyCredential` then the response also indicates that Secure Payment Confirmation is available - i.e. the response has a property `canDoSecurePaymentConfirmation` equal to `true`. 
 5. The merchant calls `show()`. If the merchant provided multiple instrument identifiers and more than one `PaymentCredential` is identified by one of the supplied identifiers (this shouldn't happen unless RPs have messed up) then the browser presents the user with an instrument selection list populated with all installed `PaymentCredentials` that are identified by provided instrument identifiers. However, the browser will prefer to use a `PaymentCredential` that is linked to a `PublicKeyCredential` so that it can offer Secure Payment Confirmation. Therefor if only one `PaymentCredential` that is identified by the supplied instrument identifiers is linked to a `PublicKeyCredential` then that `PaymentCredential` is auto-selected. If more than one `PaymentCredential` linked to a `PublicKeyCredential` is identified by the provided instrument identifiers then only those are listed for selection by the user.
 6. When the user selects an instrument (or when the browser auto-selects an instrument) the instrument identifier is passed to the merchant through an `instrumentSelected` event emitted by the Payment Request object.

### Instrument Selection Through The Browser

 1. The merchant creates a Payment Request and DOES NOT pass in instrument identifiers.
 2. The merchant calls `canMakePayment` and the browser returns a "truthy" response if at least one of the installed `PaymentCredentials` supports one of the provided payment methods. If there is an instrument linked to a `PublicKeyCredential` then the response also indicates that Secure Payment Confirmation is available - i.e. the response has a property `canDoSecurePaymentConfirmation` equal to `true`
 3. The merchant calls `show` and the browser presents the user with an instrument selection list populated with all installed `PaymentCredential`s that support the payment methods the merchant supports. 
 4. When the user selects an instrument the instrument identifier is passed to the merchant through an `instrumentSelected` event emitted by the Payment Request object.
 5. The merchant uses the instrument identifier from the event to route a request to the RP to get an optional challenge and optional fallback URL for the payment (the RP may also indicate to the merchant that no further authN is required - i.e. zero-friction - in which case the merchant exits the flow)

### AuthN

At this point the **User Provided Instrument** and **Instrument Selection Through The Browser** flows converge.

 1. The merchant passes the challenge and a fallback URL to the browser via a `respondWith` method on the `instrumentSelected` event.

 2. If the merchant provided a challenge and the selected instrument is mapped to a `PublicKeyCredential` the browser invokes Secure Payment Confirmation. The assertion generated is returned to the merchant in the `PaymentResponse`.

 3. If SPC fails or the merchant doesn't provide a challenge AND the merchant does provide a fallback URL then the browser shows a modal dialogue which renders the fallback URL and returns an instance of a `Window` to the merchant in the `PaymentResponse`. The fallback URL is only used if the origin is the same as the origin of the RP that enrolled the `PaymentCredential`. The merchant should use `postMessage` to communicate with the RP's window and can authenticate the user through some fallback mechanism such as SMS OTP.

Here's how a new simpler PR API could look with 3DS:

```javascript
// Get instrument identifiers, challenge and fallback URL from network 
const { instruments, challenge, fallbackUrl } = get3DSResponse(pan)
const request = new PaymentRequest({
  supportedMethods: ["https://mastercard.com/pay", "http://clicktopay.com/"],
  instruments // instruments = ["412938871562965", "41290981273767562"]
},{
  currency: 'USD', value: '20.00'
})

const cmp = await request.canMakePayment()
if(cmp) {
  request.addEventListener("instrumentSelected", e => {
	e.respondWith({
      challenge,
      fallbackUrl
    })
  }
  const {securePaymentConfirmation, fallbackWindow} = await request.show();

  if(securePaymentConfirmation) {
	do3DSStuff(securePaymentConfirmation)
    return
  }

  if(fallbackWindow) {
    fallbackWindow.addEventListener("message", e => {
      //Handle messages from issuer window
    })
  }
} else {
  //Legacy 3DS flow
}
```

Here's how a new simpler PR API could look WITH instrument selection:

```javascript
const request = new PaymentRequest({
  supportedMethods: ["https://mastercard.com/pay", "http://clicktopay.com/", "https://google.com/pay"],
},{
  currency: 'USD', value: '20.00'
})

const cmp = await request.canMakePayment()
if(cmp) {
  request.addEventListener("instrumentSelected", e => {
   
    if(e.supportedMethods.includes("https://google.com/pay")) {
        // Skip SPC and show Google Pay modal
		e.respondWith({
	      fallbackUrl: "https://google.com/pay?instrument=" + e.instrumentId
	    })
        return
    }

    const { challenge, fallbackUrl } = get3DSResponse(e.instrument)
    e.respondWith({
      challenge,
	  fallbackUrl
	})
  }
  const {securePaymentConfirmation, fallbackWindow} = await request.show();

  if(securePaymentConfirmation) {
	do3DSStuff(securePaymentConfirmation)
    return
  }

  if(fallbackWindow) {
    fallbackWindow.addEventListener("message", e => {
      if(e.origin == "https://google.com/")) {
        //Message from Google Pay window  
      } else {
        //Message from 3DS fallback window 
      }
    })
  }
} else {
  //Legacy checkout flow
}
```

**Comment by tblachowicz** [comment]
Thanks @adrianhopebailie, for sharing the detailed explainer of the concept! Having read the content I have a few questions of points needing clarification. I'd appreciate if you could provide your feedback to the following:

The proposal assumes there is no PH that would handle the payment, therefore there is no response provided to the merchant that would be PM-specific. In fact, the concept of Payment Method does not even apply here, because PR simply provides back the generic instrument identifier for the selected instrument and eventually result of SPC i.e. WebAuthn credential. Don't you think such an approach restricts the use of the PR API by removing the ability of PH to produce PM-specific payload, especially where the payload is dynamically generated like in SRC?

I've been wondering about the scope of the instrument identifier. Let's consider that for the payment cards, but the same applies to other payment methods similarly. Would RP (e.g. issuer/wallet) assign single instrument identifier for the card that would be used across browsers or alternatively would RP assign an instrument identifier per browser? The former is simpler, but it actually allows to identify the payment instrument across browsers, the former is more complex for both PR and eventually merchant to maintain the array of identifier per payment instrument. I'd love to know your thinking on that point.

**Comment by adrianhopebailie** [comment]
> Don't you think such an approach restricts the use of the PR API by removing the ability of PH to produce PM-specific payload, especially where the payload is dynamically generated like in SRC?

It does but my assumption here is that if the merchant has an instrument identifier (defined by the issuer/RP) and a payment method identifier then they know how to contact the issuer/RP to get whatever response they would have received from a PH.

In 3DS I think this would be done using the ARes/AReq exchange in other payment methods it may be different.

E.g. a digital wallet might decide to use URLs as instrument identifiers and the protocol for using these might be for the merchant to simply send a request to that URL.

> Would RP (e.g. issuer/wallet) assign single instrument identifier for the card that would be used across browsers or alternatively would RP assign an instrument identifier per browser?

I think it's up to the RP. The advantage of using a different identifier per browser is that it is really a combined instrument/device identifier.

> more complex for both PR and eventually merchant to maintain the array of identifier per payment instrument

Actually I think the complexity sits with the RP. E.g. An issuer might need to maintain a mapping of many identifiers for a single card but (I think) this is already the case with tokenised cards right? Each token could be an instrument identifier.

**Comment by ianbjacobs** [comment]
Regarding "Need a strategy to prevent instrument identifiers becoming global user identifiers" see #24

**Comment by ianbjacobs** [comment]
Closing since the evolving API no longer involves stored instrument data.

**Comment by bonomboni-creator** [comment]
> As a counter-proposal to [#15](https://github.com/w3c/secure-payment-confirmation/issues/15) here is a proposal that would require no Payment Handlers (i.e. they could potentially be deprecated entirely) but would require that instruments are stored by RPs in the browser using an ID that is both "routable" by a merchant and opaque enough that it is not sensitive to share.
> 
> This is a minor modification to the existing Secure Payment Confirmation (SPC) proposal.
> 
> ## Advantages:
> 1. No need for Payment Handlers = very simple to implement for RPs
> 2. Lower implementation and maintenance burden for browsers
> 3. Much simpler Payment Request API (no need to support "payment method data" and can possibly exclude shipping details etc)
> 4. Simple fallback to rendering an RP provided URL inside a modal dialogue
> 
> ## Disadvantages:
> 1. Need a strategy to prevent instrument identifiers becoming global user identifiers
> 2. No PH = no support for delegated shipping details etc
> 
> ## Assumptions:
> 1. The RP (bank/issuer/wallet) registers payment instruments in the browser at some time when the user has authenticated themselves (e.g. login to Internet banking/wallet, complete a previous transaction)
> 2. The instrument identifier is "routable" (i.e. can be used by a merchant to route an authorization request to the RP to get a challenge or fallback URL). E.g. A format-preserving tokenized card or URL
> 3. The instrument identifier is opaque (does not reveal private information about the user) as it will be revealed to the merchant before SPC when the instrument is selected by the user from a browser-rendered instrument selector
> 
> ## Questions:
> 1. Can the instrument identifier be easily rotated so it is not a global identifier shared by the browser with multiple merchants?
> 2. How does an RP register payment instruments that will not be used with Secure Payment Confirmation but where the URL for the fallback flow is not same-origin as the RP? (e.g. ACS server for capturing SMS OTP is at different origin to issuer who is the RP)
> 3. How will an RP manage the instruments installed in the user's browser? Will they be able to enumerate them, delete them etc?
> 4. Do we need a flow that is equivalent to JIT installation of a Payment Handler?
> 
> ## Enrollment
> RPs (issuers, wallets etc) will register payment instruments in a users browser during an enrolment flow which involves calling the WebAuthn `create` API to create a new `PaymentCredential`.
> 
> A `PaymentCredential` is a new type of credential which MAY be linked to a `PublicKeyCredential` (which may be implicitly created when registering the `PaymentCredential`). It contains payment instrument meta-data (i.e. a label and icon) and is mapped to one or more payment methods.
> 
> It will be possible to create a new `PaymentCredential` linked to an existing `PublicKeyCredential`. In this case the browser will invoke the authenticator's authentication flow using the details of the existing credential (as opposed to the registration flow which creates a new credential on the authenticator).
> 
> It will be possible to create a `PaymentCredential` that is not linked to a `PublicKeyCredential`. This instrument will appear in the browser-rendered instrument selector when appropriate but can't be used to invoke Secure Payment Confirmation. If a user selects one of these instruments then the merchant can only invoke the fallback authN flow by passing in an RP provided URL to render.
> 
> Whenever an RP registers an instrument there will be a user interaction whereby the user confirms the registration and their intent to use this for payments in the future. If the credential is linked to a `PublicKeyCredential` this will also involve a user interaction with their authenticator as with existing WebAuthn registration and authentication flows.
> 
> The installed `PaymentCredentials` serve multiple functions:
> 
> 1. They are used by the browser to present the user with an instrument selection list when the merchant calls PR API without providing a list of instrument identifiers. The list is filtered based on the payment methods provided by the merchant and those mapped to the credential.
> 2. The label and icon are used on the Secure Payment Confirmation screen.
> 3. The label and icon are rendered by the browser as part of the modal dialogue that renders the fallback URL when Secure Payment Confirmation is skipped/fails.
> 4. The fallback flow is only allowed if the provided URL is same-origin with the credential RP.
> 
> [SecureContext, Exposed=Window]
> interface PaymentCredential : Credential {
> };
> 
> partial dictionary CredentialCreationOptions {
>   PaymentCredentialCreationOptions securePayment;
> };
> 
> dictionary PaymentCredentialCreationOptions {
>   // |instrumentId| is a caller provided ID for the payment instrument 
>   //  to which the new PaymentCredential should be bound. It should be 
>   //  an opaque string generated using a payment network specific algorithm 
>   //  that allows the network to identify the issuer of the instrument 
>   //  and the issuer to identify the account associated with this
>   //  instrument. (e.g. form-preserving card token or URL)
> 
>   required DOMString instrumentId;
>   required DOMString displayName;
>   required USVString icon;
>   required sequence<USVString> paymentMethods;
>   PaymentCredentialPublicKeyOptions createPublicKeyCredentialOptions
>   PublicKeyCredentialDescriptor existingPublicKeyCredential;
> };
> 
> // Either |createPublicKeyCredentialOptions| or |existingPublicKeyCredential| 
> //  or both must be provided.
> // If both are provided then the browser should create the credential if 
> //  the existing credential doesn't exist.
> 
> dictionary PaymentCredentialPublicKeyCreationOptions {
>   required PublicKeyCredentialRpEntity rp;
>   required BufferSource challenge;
>   required sequence<PublicKeyCredentialParameters> pubKeyCredParams;
>   unsigned long timeout;
>   
>   // PublicKeyCredentialCreationOption attributes that are intentionally omitted:
>   // user: For a PaymentCredential, |instrument| is analogous to |user|.
>   // excludeCredentials: No payment use case has been proposed for this field.
>   // attestation: Authenticator attestation is considered an anti-pattern 
>   //  for adoption so will not be supported.
>   // extensions: No payment use case has been proposed for this field.
> };
> Example usage:
> 
> const securePaymentConfirmationCredentialCreationOptions = {
>  instrumentId: "Q1J4AwSWD4Dx6q1DTo0MB21XDAV76",
>  displayName: 'Mastercard····4444',
>  icon: 'icon.png',
>  paymentMethods: ["https://mastercard.com/pay", "https://clicktopay.com"]
>  existingCredential: {
>     type: "public-key",
>     id: Uint8Array.from(credentialId, c => c.charCodeAt(0))
>  },
>  publicKeyCreationOptions: {
>   challenge,
>   rp,
>   pubKeyCredParams,
>   timeout
>  }
> };
> 
> // Bind new credential to |credentialId|, or create a new credential 
> //  if |credentialId| doesn't exist.
> const credential = await navigator.credentials.create({
>   securePayment: securePaymentCredentialCreationOptions
> });
> ## Payment
> When a user visits a merchant there are two possible flows before Secure Payment Confirmation (or the fallback flow) is invoked.
> 
> ### User Provided Instrument
> 1. The merchant gets the instrument selection from the user via a form or other mechanism (e.g. selection of a card on file)
> 2. The merchant sources a set of valid instrument identifiers, an optional challenge, and an optional fallback URL from the payment system.
> 3. The merchant creates a Payment Request and passes the instrument identifiers into the constructor.
> 4. The merchant calls `canMakePayment` and the browser returns a "truthy" response if one of the provided instrument identifiers identifies an installed `PaymentCredential` that supports one of the merchant provided payment methods. If there is an instrument linked to a `PublicKeyCredential` then the response also indicates that Secure Payment Confirmation is available - i.e. the response has a property `canDoSecurePaymentConfirmation` equal to `true`.
> 5. The merchant calls `show()`. If the merchant provided multiple instrument identifiers and more than one `PaymentCredential` is identified by one of the supplied identifiers (this shouldn't happen unless RPs have messed up) then the browser presents the user with an instrument selection list populated with all installed `PaymentCredentials` that are identified by provided instrument identifiers. However, the browser will prefer to use a `PaymentCredential` that is linked to a `PublicKeyCredential` so that it can offer Secure Payment Confirmation. Therefor if only one `PaymentCredential` that is identified by the supplied instrument identifiers is linked to a `PublicKeyCredential` then that `PaymentCredential` is auto-selected. If more than one `PaymentCredential` linked to a `PublicKeyCredential` is identified by the provided instrument identifiers then only those are listed for selection by the user.
> 6. When the user selects an instrument (or when the browser auto-selects an instrument) the instrument identifier is passed to the merchant through an `instrumentSelected` event emitted by the Payment Request object.
> 
> ### Instrument Selection Through The Browser
> 1. The merchant creates a Payment Request and DOES NOT pass in instrument identifiers.
> 2. The merchant calls `canMakePayment` and the browser returns a "truthy" response if at least one of the installed `PaymentCredentials` supports one of the provided payment methods. If there is an instrument linked to a `PublicKeyCredential` then the response also indicates that Secure Payment Confirmation is available - i.e. the response has a property `canDoSecurePaymentConfirmation` equal to `true`
> 3. The merchant calls `show` and the browser presents the user with an instrument selection list populated with all installed `PaymentCredential`s that support the payment methods the merchant supports.
> 4. When the user selects an instrument the instrument identifier is passed to the merchant through an `instrumentSelected` event emitted by the Payment Request object.
> 5. The merchant uses the instrument identifier from the event to route a request to the RP to get an optional challenge and optional fallback URL for the payment (the RP may also indicate to the merchant that no further authN is required - i.e. zero-friction - in which case the merchant exits the flow)
> 
> ### AuthN
> At this point the **User Provided Instrument** and **Instrument Selection Through The Browser** flows converge.
> 
> 1. The merchant passes the challenge and a fallback URL to the browser via a `respondWith` method on the `instrumentSelected` event.
> 2. If the merchant provided a challenge and the selected instrument is mapped to a `PublicKeyCredential` the browser invokes Secure Payment Confirmation. The assertion generated is returned to the merchant in the `PaymentResponse`.
> 3. If SPC fails or the merchant doesn't provide a challenge AND the merchant does provide a fallback URL then the browser shows a modal dialogue which renders the fallback URL and returns an instance of a `Window` to the merchant in the `PaymentResponse`. The fallback URL is only used if the origin is the same as the origin of the RP that enrolled the `PaymentCredential`. The merchant should use `postMessage` to communicate with the RP's window and can authenticate the user through some fallback mechanism such as SMS OTP.
> 
> Here's how a new simpler PR API could look with 3DS:
> 
> // Get instrument identifiers, challenge and fallback URL from network 
> const { instruments, challenge, fallbackUrl } = get3DSResponse(pan)
> const request = new PaymentRequest({
>   supportedMethods: ["https://mastercard.com/pay", "http://clicktopay.com/"],
>   instruments // instruments = ["412938871562965", "41290981273767562"]
> },{
>   currency: 'USD', value: '20.00'
> })
> 
> const cmp = await request.canMakePayment()
> if(cmp) {
>   request.addEventListener("instrumentSelected", e => {
> 	e.respondWith({
>       challenge,
>       fallbackUrl
>     })
>   }
>   const {securePaymentConfirmation, fallbackWindow} = await request.show();
> 
>   if(securePaymentConfirmation) {
> 	do3DSStuff(securePaymentConfirmation)
>     return
>   }
> 
>   if(fallbackWindow) {
>     fallbackWindow.addEventListener("message", e => {
>       //Handle messages from issuer window
>     })
>   }
> } else {
>   //Legacy 3DS flow
> }
> Here's how a new simpler PR API could look WITH instrument selection:
> 
> const request = new PaymentRequest({
>   supportedMethods: ["https://mastercard.com/pay", "http://clicktopay.com/", "https://google.com/pay"],
> },{
>   currency: 'USD', value: '20.00'
> })
> 
> const cmp = await request.canMakePayment()
> if(cmp) {
>   request.addEventListener("instrumentSelected", e => {
>    
>     if(e.supportedMethods.includes("https://google.com/pay")) {
>         // Skip SPC and show Google Pay modal
> 		e.respondWith({
> 	      fallbackUrl: "https://google.com/pay?instrument=" + e.instrumentId
> 	    })
>         return
>     }
> 
>     const { challenge, fallbackUrl } = get3DSResponse(e.instrument)
>     e.respondWith({
>       challenge,
> 	  fallbackUrl
> 	})
>   }
>   const [{securePaymentConfirmation,](url) fallbackWindow} = await request.show();
> 
>   if(securePaymentConfirmation) {
> 	do3DSStuff(Mengkonfirmasihttps://github.com/w3c/secure-payment-confirmation/issues/17)
>     return
>   }
> 
>   if(fallbackWindow) {
>     fallbackWindow.addEventListener("message", e => {
>       if(e.origin == "https://google.com/")) {
>         //Message from Google Pay window  
>       } else {
>         //Message from 3DS fallback window 
>       }
>     })
>   }
> } else {
>   //Legacy checkout flow
> }
