### ISSUE TITLE
Term 'monkey-patch' may not be inclusive?

### ISSUE THREAD

**Issue by aphillips** [w3c/secure-payment-confirmation#207]
section 4.1.2 https://www.w3.org/TR/secure-payment-confirmation/#sctn-monkey-patch-payment-method-id

(not an I18N comment)

Is the term 'monkey-patch' inclusive? Perhaps choose a different term. In I18N's teleconference of 2022-09-08 we discussed this term and the lack of a W3C list pointing to non-inclusive language (there appears to only be a small list in specberus but nothing official??). I note that this issue has already been addressed, so feel free to close. I am *not* adding `i18n-needs-resolution` here because this is not an I18N issue.

**Comment by ianbjacobs** [comment]
We removed the phrase from our spec. Thank you for this comment; we can now close the issue.
