### ISSUE TITLE
`DOMString` for `payeeName` vs. `USVString` for other fields?

### ISSUE THREAD

**Issue by aphillips** [w3c/secure-payment-confirmation#208]
section 4.1.3 https://www.w3.org/TR/secure-payment-confirmation/#sctn-securepaymentconfirmationrequest-dictionary
section 6.1 https://www.w3.org/TR/secure-payment-confirmation/#sctn-paymentcredentialinstrument-dictionary

Oddly, `payeeName` is a `DOMString` but `payeeOrigin` is a `USVString`? This mix is found elsewhere, e.g. in "AuthenticationExtensionsClientInputs" in section 5 and in the `PaymentCredentialInstrument` dictionary in section 6.1 etc.

Is there some reason the `payeeName` needs to support unpaired surrogates?

**Comment by ianbjacobs** [comment]
@aphillips, based on our discussion today, it sounds like we should change payeeName and displayName (for the instrument) to be USVString. The currency and total are DOMStrings inherited from Payment Request API.
