### ISSUE TITLE
Include a field for the RP to provide routing information

### ISSUE THREAD

**Issue by danyao** [w3c/secure-payment-confirmation#21]
Reposting a question from @ianbjacobs:

Should we include a field for the RP to provide routing information, rather than assuming that the instrument id will carry the routing information in all cases? The field might be optional. But, for example, it would easily map to systems like ACH (routing number, account number).

**Comment by ianbjacobs** [comment]
Because we are deprioritizing instrument selection for now, I am closing this issue. We can return to it later.
