### ISSUE TITLE
How to include the transaction details in the FIDO/WebAuthn assertion

### ISSUE THREAD

**Issue by rlin1** [w3c/secure-payment-confirmation#23]
Proposal: The Browser could crptographically link the transaction details to the FIDO assertion via an additional field in the "collectedClientData"

**Comment by danyao** [comment]
Thanks for opening an issue.

Actually this is already part of the [design][1] but looks like it's not clearly stated in the explainer. I'll fix this.

[1]: https://docs.google.com/document/d/16QDToTqx7QIOIH4C0bTlPbuMDpg9ZEeEGdfCOpQdaV8/edit#heading=h.4yz4b8uzoxna

**Comment by ianbjacobs** [comment]
@danyao, can we close this issue?

**Comment by danyao** [comment]
Yep.
