### ISSUE TITLE
Provide support for Out of Band Authentication to a secondary device

### ISSUE THREAD

**Issue by Goosth** [w3c/secure-payment-confirmation#30]
We should probably consider other flows defined inside 3DS 2.0. 
Consider a situation where the current device has not yet been setup/registered for WebAuthn, but another device linked to this user has have been setup. This is very probable in a Guest shopping scenario.

Out of Band authentication allows the browser to reach out a second device (typically a mobile phone the user carries with them) where the transaction is approved.

Note that we're not talking about using OTP's here, but rather the ability to reach out to a second device and activate the Authentication (e.g. a WebAuthn Platform Authenticator) on that device. If this is is something we can design in should achieve much higher adoption, since a user will not have to have their Fido Authenticator setup on all devices that they own.

**Comment by ianbjacobs** [comment]
@Goosth,

Would this text in the "scope" document capture your use case?

* While mobile banking, Alice enrolls the authenticator in her phone to be used with all her credit cards issued by this bank.
* While shopping on a desktop browser, Alice initiates a checkout.
* She receives a push notification on her phone to authenticate with that device for the transaction.
* Upon successful authentication, the checkout experience on her desktop successfully completes.

**Comment by Goosth** [comment]
@ianbjacobs,

This should do the trick, yes. 

You might want to also consider the use-case where Alice is using a mobile browser, and the authenticator app is on the same device. In this case an redirect/intent fired to the app may work better; and then a subsequent redirect back to the browser once authentication is recieved.

Also perhaps worthwhile to note, that there are two typical API patterns for doing this:
* Callout to third party address and wait for callback (to dedicated callback URL/service)
* Callout to third party and then poll until outcome (Approve/decline/failure such as timeout) is received. This might work better for web.
Also note that this out of band channel/authenticator would then do a full SCA approval. It could in fact use a Fido token on that second device (mobile phone).

**Comment by ianbjacobs** [comment]
Hi @goosth,

At today's call [1] I heard no interest in using SPC for out-of-band use cases. Should we close this issue?

[1] https://www.w3.org/2021/06/24-wpwg-minutes

**Comment by Goosth** [comment]
Hi @ianbjacobs ,

Would agree with this assessment. 

Our thinking on SPC is now a much more simpler format, where fallback URL's and other flows are not included anymore. Between Fido's work to support 'Mobile as External Authenticator' and planned solution space for SPC, this would be solvable by 
* Showing a web page on the primary display
* Reaching out to the second device via some other back-channel protocol
* Using SPC on that second device if it is a browser.

Will close this issue.

**Comment by ianbjacobs** [comment]
I am not re-opening this issue, but the use case that @Goosth refers to may be addressed in Web Authentication via the public key extension: https://github.com/w3c/webauthn/pull/1663
