### ISSUE TITLE
Are Client-side Discoverable Credentials (aka Resident Keys) off the table in this proposal?

### ISSUE THREAD

**Issue by SensibleWood** [w3c/secure-payment-confirmation#31]
Just wondering what the approach is for Client-side Discoverable Credentials is? (Just for ease, here's their [definition](https://www.w3.org/TR/webauthn-2/#client-side-discoverable-credential)).

From the examples the querying function appears to replace it, but that has implications for the inherent advantages of discovery, especially in usability i.e. the RP in this context (the Merchant - not the origin) will "always" have to "know" the Credential identifier. From the perspective of user experience it would great to allow a "natural" selection of the credential at the Authenticator, with some visual prompts for the user.

Leveraging the discoverable credentials approach could allow for the actual payment instrument - lets say it's a payment card - to be stored within the Authenticator using a Level 2 mechanism such as [credential properties](https://www.w3.org/TR/webauthn-2/#sctn-authenticator-credential-properties-extension). This would allow for a belt-and-braces approach where the Authenticator delivers both the authentication event and the secured instrument data.

**Comment by ianbjacobs** [comment]
Hi @SensibleWood, let's talk about use cases that could leverage Discoverable Credentials at the upcoming FTF meeting. 

Do you have a specific flow in mind?

**Comment by ianbjacobs** [comment]
See also issue #92

**Comment by ianbjacobs** [comment]
@SensibleWood, should we close this issue in favor of #92, which places the question in more recent context?

**Comment by SensibleWood** [comment]
> @SensibleWood, should we close this issue in favor of #92, which places the question in more recent context?

Sure - this has moved on - closing...
