### ISSUE TITLE
Unable to "decipher" sequence diagram

### ISSUE THREAD

**Issue by cyberphone** [w3c/secure-payment-confirmation#41]
When looking at https://github.com/rsolomakhin/secure-payment-confirmation/blob/master/sequence-diagrams/SecurePaymentConfirmation-Pilot-Checkout.png I fail linking it to 3DS. In my understanding, 3DS is a separate (additional) card-holder authentication process performed _before_ the actual payment process is initiated.

In the last part of the mentioned sequence diagram it seems that the ACS is the same as a payment initiation end-point.   That is not how the existing 3DS ecosystem works.

Am I missing something here?

I would consider making a less crammed version of sequence diagram where each step is _numbered_, making it possible to put explanatory data in text outside of the diagram.

@danyao

**Comment by ianbjacobs** [comment]
I am closing this issue because the sequence diagram is not (at this time at least) driving discussions. We may return to this later in the development of the API, at which time we can reopen it.
