### ISSUE TITLE
Change payment amount from SPC call within a payment app?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#42]
I spoke with Frank Hoffmann today who asked whether it would be possible for a payment app that calls SPC (assuming it can) to change the total.

The use case is:

 * User agrees with merchant to pay $100
 * When user chooses payment method, the payment method supports installments (e.g., $25 every week)
 * The SPC transaction window should say "Do you agree to pay $25?" 
 * Subsequent payments are handled by card-on-file

Ian

**Comment by danyao** [comment]
> * User agrees with merchant to pay $100

What constitute an "agreement"? Who, if any, needs to be able to verify this "agreement" took place?

> * When user chooses payment method, the payment method supports installments (e.g., $25 every week)
> * The SPC transaction window should say "Do you agree to pay $25?"

This sounds like the browser UI should display $25. What would be the amount that the issuer wants to see in the Transaction Confirmation / Dynamic Linking signature?

> * Subsequent payments are handled by card-on-file

Do these subsequent payments need to carry Dynamic Linking signatures?

**Comment by ianbjacobs** [comment]
cc @frank-hoffmann

**Comment by ianbjacobs** [comment]
The way the API has evolved, if it is callable at all in a payment handler, then it is callable with data provided by the payment handler. So the answer to the original issue is "Yes, the payment handler can specify a total that is different from what the merchant displayed." The resulting assertion will include the signed data that was displayed, and the RP can accept or reject it.
