### ISSUE TITLE
Allow enrollment outside of transaction flow

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#44]
I would like to hear from people whether it is important to allow credential enrollment outside a Payment Request flow. For example, I visit my payment provider (BobPay) and enroll my authenticator for a future SPC payment.

**Comment by tblachowicz** [comment]
Yes, this is an important feature. It can be BobPay or a Bank who would enroll the Payment Instrument into the browser so it can be used by merchants to trigger authentication/confirmation with SPC.

**Comment by ianbjacobs** [comment]
I am closing this issue. At this point nothing suggests that the API prevents enrollment outside the transaction flow.
