### ISSUE TITLE
Rich merchant details displayed in the payment confirmation dialog

### ISSUE THREAD

**Issue by tblachowicz** [w3c/secure-payment-confirmation#48]
Currently, in the pilot implementation, only the domain name of the merchant website is displayed in the payment confirmation dialog. I'd like to propose to enhance the visual representation of the merchant by displaying also the title and favicon of the page from which SPC request has been triggered. Of course, it's the subject of the availability of the data.

**Comment by stephenmcgruer** [comment]
For reference, this is the current UX in Chromium - albeit note that a browser is able to implement this as they wish as long as they meet the [spec requirements](https://w3c.github.io/secure-payment-confirmation/#sctn-transaction-confirmation-ux).

![image](https://user-images.githubusercontent.com/153264/156608896-3e1b1d7d-fc85-415f-ba1a-03cce3a3de11.png)

The caller-specified fields shown here map to (from top-to-bottom, left-to-right):

- `payeeOrigin`
- `instrument.icon`
- `instrument.displayName`
- `amount.currency` ([from PaymentRequest](https://w3c.github.io/payment-request/#paymentcurrencyamount-dictionary))
- `amount.value`

**Comment by ianbjacobs** [comment]
After discussion with the Chairs and Editors we are closing this issue having added payeeName to the display as a result of a separate issue. We also anticipate other more specific issues are going to be opened as a result of EMVCo review of the API, and so are closing this one.
