### ISSUE TITLE
Does the API support timeout?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#67]
Raised in discussion with @goosth:

* The transaction confirmation dialog opens
* The user does not authenticate or cancel within some time frame.

What happens? Are there timeout parameters?

**Comment by rsolomakhin** [comment]
`PaymentRequest` object has an `abort()` method that can be triggered from a `window.setTimeout()` call. Would that satisfy the requirements of the API users?

**Comment by ianbjacobs** [comment]
Closing this because the API supports timeout:
https://w3c.github.io/secure-payment-confirmation/#dom-securepaymentconfirmationrequest-timeout
