### ISSUE TITLE
When SPC runs in an iframe, what permissions are required?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#68]
Raised by @Goosth

**Comment by stephenmcgruer** [comment]
From the browser side, we (Chromium) are likely to require the `payments` policy (https://w3c.github.io/payment-request/#permissions-policy) or some equivalent for any cross-origin iframe case.

Additionally, outside of the iframe specific question, we will also expect SPC to consume a user activation (e.g. a click), or a [capability delegation token](https://github.com/WICG/capability-delegation) if/when that spec matures.

**Comment by stephenmcgruer** [comment]
The "Buy" button click is a user activation, so whether or not we support the 'Frictionless Checkout' flow wouldn't fall under that concern. I haven't thought through the full privacy/user-expectation implications of a completely frictionless flow yet though :D.

**Comment by stephenmcgruer** [comment]
@ianbjacobs - I don't think there's much else to discuss here currently, so I'm going to close this issue. Please feel free to reopen if you think there's still something to be addressed.
