### ISSUE TITLE
Can a merchant ensure that SPC will be used before invoking PR API?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/secure-payment-confirmation#8]
It would be ideal if a merchant could construct a PR object and use the output of `canMakePayment` to determine if SPC is possible.

```javascript
const cmp = await pr.canMakePayment()
if(cmp.canDoSecurePaymentConfirmation) {
  //Yay! Frictionless, secure, payments FTW!
  const result = pr.show()
} else {
  //Boo! [fall back to traditional flow]
```

This would be for the case when the merchant is depending on the browser to provide an instrument selector and then a PH would be invoking SPC

**Comment by danyao** [comment]
Makes sense. I'd want to make sure we can do this without sending any data to the payment handler first, and I think it is possible.

Rough algorithm to compute `canDoSecurePaymentConfirmation`:

1. If the requested payment method doesn't match any already registered payment handler, return `false`.
1. Let `requestInstrumentId` be the `instrumentId` provided in the request or `null`
1. For each payment handler that matches the requested payment method:
    1. If `requestInstrumentId` is not `null` and `requestInstrument` does not match any instrument Id in this payment handler's registration, continue.
    1. For each `paymentHandlerInstrumentId` in this payment handler's registration:
        1. If a `SecurePaymentCredential` exists on the current device for `paymentHandlerInstrumentId`, return `true`.
1. Return `false`.

**Comment by ianbjacobs** [comment]
I think this issue was raised at a time when (1) we expected payment handler support at least for SPC enrollment and (2) we anticipated instrument selection would happen within a payment handler.

At this point SPC's design does not require a payment handler. Instrument selection is done before SPC is called.
